# Generated by Django 5.0.4 on 2024-05-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principalapp', '0002_proveedores_productos_categoria_marcas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('charms', 'charms'), ('aretes', 'aretes'), ('anillos', 'anillos'), ('brazaletes', 'brazaletes'), ('collares', 'collares')], default='categoria1', max_length=20),
        ),
    ]
