# Generated by Django 5.0.4 on 2024-05-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principalapp', '0003_alter_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principalapp.marcas'),
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principalapp.proveedores'),
        ),
    ]
