# Generated by Django 5.0.4 on 2024-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principalapp', '0004_productos_marca_productos_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
